### ISSUE TITLE
IE8 Problem

### ISSUE THREAD

**Issue by ahmetsali** [michael-lynch/reading-time#15]
Hi, i get this error on console on I8. Is it possible to make this plugin compatible with IE8 ?

Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)
Timestamp: Fri, 4 Jul 2014 19:14:57 UTC

Message: Object doesn't support this property or method
Line: 12
Char: 999
Code: 0
URI: http://michael-lynch.github.io/reading-time/js/readingTime.min.js

**Comment by ciriac** [comment]
It looks like line 120 is causing the issue on IE8. I solved this by using jQuery's $.trim instead of .trim().

**Comment by ahmetsali** [comment]
@ciriac thanks for the solution.
