### ISSUE TITLE
readingTimeTarget anywhere

### ISSUE THREAD

**Issue by JeanLucEsser** [michael-lynch/reading-time#21]
I ran into two issues while using this otherwise awesome plugin:

First, it looks like we are unable to target a class anywhere we want in the page with readingTimeTarget. It has to be within the targeted article. This has serious limitations if we have a specific design and while we can move the span around on success via jquery, it is not ideal.

Second, it would be nice to have an option to return only the number of minutes, without "min" appended to it. Better yet, two append options (singular/plural), but it may overcomplicate...

**Comment by bilalbaraz** [comment]
As you would like, reading time was added as integer by me. I've created pull request.
