### ISSUE TITLE
"each" method doesn't work with laravel foreach

### ISSUE THREAD

**Issue by BechirAhmed** [michael-lynch/reading-time#32]
I tried to use it with laravel in foreach, i want it to be displayed on every post, but it take only the last post in foreach loop and add the time & word-count to all other posts, 
`foreach`
`<div class="hidden" id="articleDesc">{{ $relatedPost->description }}</div>`
`<span class="eta"></span>`
 `<span class="word-count"></span>`
`endforeach`
`$(function() {`
`          $('#articleDesc').each(function() {`
 `           $(this).readingTime({`
 `             readingTimeTarget: '.eta',`
 `             wordCountTarget: '.word-count',`
 `           });`
 `         });`
`        });`

**Comment by michael-lynch** [comment]
You're targeting _all_ instances of `.eta` and `.word-count`, so yes, the last iteration of your loop will update all of them. You just need to use `$(this)` to target each specific instance.

```
$('#articleDesc').each(function() {
    $(this).readingTime({
        readingTimeTarget: $(this).find('.eta'),
        wordCountTarget: $(this).find('.word-count')
    });
});
```
